### ISSUE TITLE
Agency filing statistics

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-epics#192]
## What we’re after
To become more transparent about the amount of data that is being processed by the FEC each month, we want to use the API to display report processing and transaction count data.

## Tickets
- [x] fecgov/openFEC#4694

### Things to look at

Research if we can utilize the /operations-log/ endpoint: https://api.open.fec.gov/developers/#/filings/get_operations_log_ 
This endpoint only contains the operations-log table. We’ll need additional tables for calculating these percentages and counts.

**Example API call:** https://api.open.fec.gov/v1/operations-log/?sort_nulls_last=false&sort=-report_year&per_page=100&sort_hide_null=true&sort_null_only=false&api_key=DEMO_KEY&page=1

**Try to start with high overview of data first:**
- Number of transactions per month
   - Row for each day that can be aggregated to create a monthly transaction total.
- Report processing (Processed vs unprocessed data filings percentages)
   - Transaction_data_complete_date - used for reports that are processed. If null then it is not complete.

**Comment by PaulClark2** [comment]
Closing for now, we can revisit later.
