### ISSUE TITLE
eRegs Django and python parser upgrade

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-epics#205]
**What we’re after:** We need to upgrade Django to remediate security vulnerabilities. In addition, we need to upgrade the python version in the parser.

**Why we’re after it:** So that we can lessen the tech debt for our eRegulations application.

**Comment by pkfec** [comment]
fec-eregs is now running on Django LTS v3.2.10. PR is merged here  fecgov/fec-eregs#647. Closing this issue
