### ISSUE TITLE
Pattern Library 

### ISSUE THREAD

**Issue by adrianwebb** [fecgov/fec-epics#79]
**What we’re after:** We need to complete the FEC pattern library to include all patterns currently in use on the site and rationale and documentation around their use. This will likely also end up including fine tuning of patterns as we document them and refactoring aspects of the front-end code. 

**Why we’re after it:** We want to make the design system as easy to apply as possible for future developers and designers within and outside the FEC.

**Comment by jenniferthibault** [comment]
Edited to update description
